name: Docker
on:
  workflow_dispatch:
  workflow_run:
    branches: [main]
    workflows: [Build]
    types: [completed]

env:
  image_name: "evergreendashboard"
  image_tag: "latest"

jobs:
  build_docker_image:
    name: build docker image
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}:${{ env.image_tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
